#Requires -Version 7.0
#Requires -PSEdition Core

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('show', 'set', 'bump', 'verify')]
    [string] $Command = 'show',

    [string] $Version,

    [ValidateSet('major', 'minor', 'patch')]
    [string] $Part,

    [AllowEmptyString()]
    [string] $Prerelease,

    [string] $RepositoryRoot,

    [string] $PublishedDirectory,

    [string] $Tag,

    [switch] $RequireClean,

    [switch] $DryRun,

    [switch] $Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$MaximumVersionComponent = 65534
$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$VersionPattern = [System.Text.RegularExpressions.Regex]::new(
    '^(?<major>0|[1-9][0-9]*)\.(?<minor>0|[1-9][0-9]*)\.(?<patch>0|[1-9][0-9]*)(?:-(?<prerelease>[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$',
    [System.Text.RegularExpressions.RegexOptions]::CultureInvariant)
$VersionPrefixElementPattern = [System.Text.RegularExpressions.Regex]::new(
    '<VersionPrefix>(?<value>[^<]*)</VersionPrefix>',
    [System.Text.RegularExpressions.RegexOptions]::CultureInvariant)
$VersionSuffixElementPattern = [System.Text.RegularExpressions.Regex]::new(
    '<VersionSuffix>(?<value>[^<]*)</VersionSuffix>',
    [System.Text.RegularExpressions.RegexOptions]::CultureInvariant)

function Assert-SupportedHost {
    if ($PSVersionTable.PSEdition -cne 'Core' -or $PSVersionTable.PSVersion.Major -lt 7) {
        throw 'PowerShell Core 7 or later is required. Windows PowerShell is not supported.'
    }
}

function Resolve-ApplicationPath {
    param(
        [Parameter(Mandatory)]
        [string] $Name
    )

    $command = Get-Command $Name -CommandType Application -ErrorAction Stop |
        Select-Object -First 1
    if ($null -eq $command -or [string]::IsNullOrWhiteSpace([string]$command.Source)) {
        throw "Unable to resolve application command: $Name"
    }

    return [string]$command.Source
}

function Resolve-RepositoryRoot {
    if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) {
        return [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
    }

    return [System.IO.Path]::GetFullPath($RepositoryRoot)
}

function ConvertTo-VersionComponent {
    param(
        [Parameter(Mandatory)]
        [string] $Value,

        [Parameter(Mandatory)]
        [string] $Name
    )

    $number = [System.Numerics.BigInteger]::Parse(
        $Value,
        [System.Globalization.CultureInfo]::InvariantCulture)
    if ($number -gt $MaximumVersionComponent) {
        throw "The $Name component exceeds the repository limit $MaximumVersionComponent."
    }

    return [int]$number
}

function ConvertFrom-ProductVersion {
    param(
        [Parameter(Mandatory)]
        [string] $Value
    )

    if ([string]::IsNullOrWhiteSpace($Value) -or
        -not [string]::Equals($Value, $Value.Trim(), [System.StringComparison]::Ordinal) -or
        $Value.Contains('+', [System.StringComparison]::Ordinal)) {
        throw 'Product version must be SemVer MAJOR.MINOR.PATCH with an optional prerelease suffix; build metadata is generated by the .NET SDK.'
    }

    $match = $VersionPattern.Match($Value)
    if (-not $match.Success) {
        throw "Invalid product version: $Value"
    }

    $prerelease = $match.Groups['prerelease'].Value
    if ($prerelease.Length -gt 0) {
        foreach ($identifier in $prerelease.Split('.', [System.StringSplitOptions]::None)) {
            if ($identifier.Length -eq 0 -or
                ($identifier -match '^[0-9]+$' -and
                 $identifier.Length -gt 1 -and
                 $identifier[0] -eq '0')) {
                throw "Invalid product version prerelease identifier: $identifier"
            }
        }
    }

    $major = ConvertTo-VersionComponent -Value $match.Groups['major'].Value -Name 'MAJOR'
    $minor = ConvertTo-VersionComponent -Value $match.Groups['minor'].Value -Name 'MINOR'
    $patch = ConvertTo-VersionComponent -Value $match.Groups['patch'].Value -Name 'PATCH'
    $core = "$major.$minor.$patch"
    $normalized = if ($prerelease.Length -eq 0) {
        $core
    }
    else {
        "$core-$prerelease"
    }

    return [pscustomobject]@{
        Version = $normalized
        Core = $core
        Major = $major
        Minor = $minor
        Patch = $patch
        Prerelease = $prerelease
        IsPrerelease = $prerelease.Length -gt 0
    }
}

function Get-VersionSource {
    param(
        [Parameter(Mandatory)]
        [string] $Root
    )

    $path = Join-Path $Root 'Directory.Build.props'
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Version source does not exist: $path"
    }

    $item = Get-Item -LiteralPath $path -Force
    if (($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
        throw "The version source must not be a reparse point: $path"
    }

    $text = [System.IO.File]::ReadAllText($path)
    $prefixResults = $VersionPrefixElementPattern.Matches($text)
    $suffixResults = $VersionSuffixElementPattern.Matches($text)
    if ($prefixResults.Count -ne 1 -or $suffixResults.Count -ne 1) {
        throw 'Directory.Build.props must contain exactly one VersionPrefix and one VersionSuffix element.'
    }

    $prefix = $prefixResults[0].Groups['value'].Value
    $suffix = $suffixResults[0].Groups['value'].Value
    $combined = if ($suffix.Length -eq 0) { $prefix } else { "$prefix-$suffix" }
    $parsed = ConvertFrom-ProductVersion -Value $combined
    if (-not [string]::Equals($parsed.Core, $prefix, [System.StringComparison]::Ordinal) -or
        -not [string]::Equals($parsed.Prerelease, $suffix, [System.StringComparison]::Ordinal)) {
        throw 'VersionPrefix or VersionSuffix is not in normalized repository form.'
    }

    return [pscustomobject]@{
        Path = $path
        Text = $text
        Prefix = $prefix
        Suffix = $suffix
        Parsed = $parsed
    }
}

function Set-SingleElementValue {
    param(
        [Parameter(Mandatory)]
        [string] $Text,

        [Parameter(Mandatory)]
        [System.Text.RegularExpressions.Regex] $Pattern,

        [Parameter(Mandatory)]
        [string] $ElementName,

        [AllowEmptyString()]
        [string] $Value
    )

    $elementResults = $Pattern.Matches($Text)
    if ($elementResults.Count -ne 1) {
        throw "Expected exactly one $ElementName element."
    }

    $match = $elementResults[0]
    $replacement = "<$ElementName>$Value</$ElementName>"
    return $Text.Substring(0, $match.Index) +
        $replacement +
        $Text.Substring($match.Index + $match.Length)
}

function Set-VersionSource {
    param(
        [Parameter(Mandatory)]
        [psobject] $Source,

        [Parameter(Mandatory)]
        [psobject] $Target,

        [switch] $WhatIfOnly
    )

    if ([string]::Equals(
            $Source.Parsed.Version,
            $Target.Version,
            [System.StringComparison]::Ordinal)) {
        return $false
    }

    if ($WhatIfOnly) {
        return $true
    }

    $updated = Set-SingleElementValue `
        -Text $Source.Text `
        -Pattern $VersionPrefixElementPattern `
        -ElementName 'VersionPrefix' `
        -Value $Target.Core
    $updated = Set-SingleElementValue `
        -Text $updated `
        -Pattern $VersionSuffixElementPattern `
        -ElementName 'VersionSuffix' `
        -Value $Target.Prerelease

    $directory = [System.IO.Path]::GetDirectoryName($Source.Path)
    $temporaryPath = Join-Path $directory ('.Directory.Build.props.' + [System.Guid]::NewGuid().ToString('N') + '.tmp')
    try {
        [System.IO.File]::WriteAllText($temporaryPath, $updated, $Utf8NoBom)
        [System.IO.File]::Move($temporaryPath, $Source.Path, $true)
    }
    finally {
        if (Test-Path -LiteralPath $temporaryPath) {
            Remove-Item -LiteralPath $temporaryPath -Force
        }
    }

    return $true
}

function Get-EvaluatedProjectVersion {
    param(
        [Parameter(Mandatory)]
        [string] $DotNetPath,

        [Parameter(Mandatory)]
        [string] $ProjectPath
    )

    if (-not (Test-Path -LiteralPath $ProjectPath -PathType Leaf)) {
        throw "Project does not exist: $ProjectPath"
    }

    $output = & $DotNetPath msbuild $ProjectPath `
        -nologo `
        '-getProperty:Version,VersionPrefix,VersionSuffix'
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) {
        throw "dotnet msbuild failed for $ProjectPath with exit code $exitCode."
    }

    try {
        $result = (([string](@($output) -join "`n")).Trim() | ConvertFrom-Json)
    }
    catch {
        throw "dotnet msbuild returned invalid version property JSON for $ProjectPath."
    }

    return [pscustomobject]@{
        Project = [System.IO.Path]::GetFullPath($ProjectPath)
        Version = [string]$result.Properties.Version
        VersionPrefix = [string]$result.Properties.VersionPrefix
        VersionSuffix = [string]$result.Properties.VersionSuffix
    }
}

function Assert-PublishedAssemblyVersion {
    param(
        [Parameter(Mandatory)]
        [string] $AssemblyPath,

        [Parameter(Mandatory)]
        [psobject] $Expected
    )

    if (-not (Test-Path -LiteralPath $AssemblyPath -PathType Leaf)) {
        throw "Published assembly does not exist: $AssemblyPath"
    }

    $assemblyVersion = [System.Reflection.AssemblyName]::GetAssemblyName($AssemblyPath).Version
    $versionInfo = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($AssemblyPath)
    $productVersion = ([string]$versionInfo.ProductVersion).Split('+', 2)[0]
    $expectedNumeric = "$($Expected.Core).0"
    if (-not [string]::Equals($assemblyVersion.ToString(), $expectedNumeric, [System.StringComparison]::Ordinal) -or
        -not [string]::Equals([string]$versionInfo.FileVersion, $expectedNumeric, [System.StringComparison]::Ordinal) -or
        -not [string]::Equals($productVersion, $Expected.Version, [System.StringComparison]::Ordinal)) {
        throw "Published assembly version mismatch: $AssemblyPath"
    }

    return [pscustomobject]@{
        Path = $AssemblyPath
        AssemblyVersion = $assemblyVersion.ToString()
        FileVersion = [string]$versionInfo.FileVersion
        ProductVersion = [string]$versionInfo.ProductVersion
    }
}

function Assert-GitTag {
    param(
        [Parameter(Mandatory)]
        [string] $Root,

        [Parameter(Mandatory)]
        [string] $ExpectedVersion,

        [Parameter(Mandatory)]
        [string] $TagName
    )

    $expectedTag = "v$ExpectedVersion"
    if (-not [string]::Equals($TagName, $expectedTag, [System.StringComparison]::Ordinal)) {
        throw "Tag must exactly match the product version: expected $expectedTag."
    }

    $gitPath = Resolve-ApplicationPath -Name 'git'
    $tagType = ([string](@(& $gitPath -C $Root cat-file -t "refs/tags/$TagName") -join '')).Trim()
    if ($LASTEXITCODE -ne 0 -or $tagType -cne 'tag') {
        throw "Release tag must exist and be annotated: $TagName"
    }

    $tagCommit = ([string](@(& $gitPath -C $Root rev-list -n 1 $TagName) -join '')).Trim()
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($tagCommit)) {
        throw "Unable to resolve release tag commit: $TagName"
    }

    $headCommit = ([string](@(& $gitPath -C $Root rev-parse HEAD) -join '')).Trim()
    if ($LASTEXITCODE -ne 0 -or
        -not [string]::Equals($tagCommit, $headCommit, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Release tag $TagName does not identify HEAD."
    }

    return [pscustomobject]@{
        Name = $TagName
        Commit = $tagCommit
        Annotated = $true
    }
}

function Assert-CleanWorkingTree {
    param(
        [Parameter(Mandatory)]
        [string] $Root
    )

    $gitPath = Resolve-ApplicationPath -Name 'git'
    $status = @(& $gitPath -C $Root status --porcelain=v1 --untracked-files=all)
    if ($LASTEXITCODE -ne 0) {
        throw 'Unable to inspect the Git working tree.'
    }

    if ($status.Count -ne 0) {
        throw "Release verification requires a clean working tree; found $($status.Count) status entries."
    }
}

function Assert-Changelog {
    param(
        [Parameter(Mandatory)]
        [string] $Root,

        [string] $ReleasedVersion
    )

    $path = Join-Path $Root 'CHANGELOG.md'
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "CHANGELOG does not exist: $path"
    }

    $text = [System.IO.File]::ReadAllText($path)
    $unreleasedPattern = [System.Text.RegularExpressions.Regex]::new(
        '(?m)^## \[Unreleased\][ \t]*\r?$',
        [System.Text.RegularExpressions.RegexOptions]::CultureInvariant)
    if ($unreleasedPattern.Matches($text).Count -ne 1) {
        throw 'CHANGELOG.md must contain exactly one [Unreleased] section.'
    }

    if (-not [string]::IsNullOrWhiteSpace($ReleasedVersion)) {
        $escapedVersion = [System.Text.RegularExpressions.Regex]::Escape($ReleasedVersion)
        $releasePattern = [System.Text.RegularExpressions.Regex]::new(
            "(?m)^## \[$escapedVersion\] - [0-9]{4}-[0-9]{2}-[0-9]{2}[ \t]*\r?$",
            [System.Text.RegularExpressions.RegexOptions]::CultureInvariant)
        if ($releasePattern.Matches($text).Count -ne 1) {
            throw "CHANGELOG.md must contain exactly one dated section for $ReleasedVersion."
        }
    }

    return $path
}

function Write-CommandResult {
    param(
        [Parameter(Mandatory)]
        [psobject] $Result
    )

    if ($Json) {
        $Result | ConvertTo-Json -Depth 8
        return
    }

    $Result | Format-List | Out-String | Write-Output
}

Assert-SupportedHost
$root = Resolve-RepositoryRoot
$source = Get-VersionSource -Root $root

switch ($Command) {
    'show' {
        Write-CommandResult -Result ([pscustomobject]@{
            Status = 'PASS'
            Command = 'show'
            Version = $source.Parsed.Version
            VersionPrefix = $source.Prefix
            VersionSuffix = $source.Suffix
            Source = $source.Path
        })
    }

    'set' {
        if ([string]::IsNullOrWhiteSpace($Version)) {
            throw 'The set command requires -Version.'
        }

        if ($PSBoundParameters.ContainsKey('Part') -or $PSBoundParameters.ContainsKey('Prerelease')) {
            throw 'The set command accepts -Version, not -Part or -Prerelease.'
        }

        $target = ConvertFrom-ProductVersion -Value $Version
        $changed = Set-VersionSource -Source $source -Target $target -WhatIfOnly:$DryRun
        Write-CommandResult -Result ([pscustomobject]@{
            Status = 'PASS'
            Command = 'set'
            PreviousVersion = $source.Parsed.Version
            Version = $target.Version
            Changed = $changed
            DryRun = [bool]$DryRun
            Source = $source.Path
        })
    }

    'bump' {
        if ([string]::IsNullOrWhiteSpace($Part)) {
            throw 'The bump command requires -Part major, minor, or patch.'
        }

        if ($PSBoundParameters.ContainsKey('Version')) {
            throw 'The bump command accepts -Part, not -Version.'
        }

        $major = $source.Parsed.Major
        $minor = $source.Parsed.Minor
        $patch = $source.Parsed.Patch
        switch ($Part) {
            'major' {
                $major++
                $minor = 0
                $patch = 0
            }
            'minor' {
                $minor++
                $patch = 0
            }
            'patch' {
                $patch++
            }
        }

        if ($major -gt $MaximumVersionComponent -or
            $minor -gt $MaximumVersionComponent -or
            $patch -gt $MaximumVersionComponent) {
            throw "The requested bump exceeds the repository limit $MaximumVersionComponent."
        }

        $suffix = if ($PSBoundParameters.ContainsKey('Prerelease')) { $Prerelease } else { '' }
        $targetText = "$major.$minor.$patch"
        if (-not [string]::IsNullOrEmpty($suffix)) {
            $targetText += "-$suffix"
        }

        $target = ConvertFrom-ProductVersion -Value $targetText
        $changed = Set-VersionSource -Source $source -Target $target -WhatIfOnly:$DryRun
        Write-CommandResult -Result ([pscustomobject]@{
            Status = 'PASS'
            Command = 'bump'
            Part = $Part
            PreviousVersion = $source.Parsed.Version
            Version = $target.Version
            Changed = $changed
            DryRun = [bool]$DryRun
            Source = $source.Path
        })
    }

    'verify' {
        if ($PSBoundParameters.ContainsKey('Version') -or
            $PSBoundParameters.ContainsKey('Part') -or
            $PSBoundParameters.ContainsKey('Prerelease') -or
            $DryRun) {
            throw 'The verify command does not accept -Version, -Part, -Prerelease, or -DryRun.'
        }

        $dotNetPath = Resolve-ApplicationPath -Name 'dotnet'
        $projectPaths = @(
            (Join-Path $root 'src\StudyReportEvaluator.Core\StudyReportEvaluator.Core.csproj'),
            (Join-Path $root 'src\StudyReportEvaluator.App\StudyReportEvaluator.App.csproj')
        )
        $projects = @()
        foreach ($projectPath in $projectPaths) {
            $evaluated = Get-EvaluatedProjectVersion -DotNetPath $dotNetPath -ProjectPath $projectPath
            if (-not [string]::Equals($evaluated.Version, $source.Parsed.Version, [System.StringComparison]::Ordinal) -or
                -not [string]::Equals($evaluated.VersionPrefix, $source.Prefix, [System.StringComparison]::Ordinal) -or
                -not [string]::Equals($evaluated.VersionSuffix, $source.Suffix, [System.StringComparison]::Ordinal)) {
                throw "Evaluated project version does not match Directory.Build.props: $projectPath"
            }

            $projects += $evaluated
        }

        $changelogPath = Assert-Changelog -Root $root

        $assemblies = @()
        if (-not [string]::IsNullOrWhiteSpace($PublishedDirectory)) {
            $publishedRoot = if ([System.IO.Path]::IsPathRooted($PublishedDirectory)) {
                [System.IO.Path]::GetFullPath($PublishedDirectory)
            }
            else {
                [System.IO.Path]::GetFullPath($PublishedDirectory, $root)
            }

            foreach ($fileName in @('StudyReportEvaluator.Core.dll', 'StudyReportEvaluator.App.dll')) {
                $assemblies += Assert-PublishedAssemblyVersion `
                    -AssemblyPath (Join-Path $publishedRoot $fileName) `
                    -Expected $source.Parsed
            }
        }

        $tagResult = $null
        if (-not [string]::IsNullOrWhiteSpace($Tag)) {
            [void](Assert-Changelog -Root $root -ReleasedVersion $source.Parsed.Version)
            $tagResult = Assert-GitTag -Root $root -ExpectedVersion $source.Parsed.Version -TagName $Tag
        }

        if ($RequireClean) {
            Assert-CleanWorkingTree -Root $root
        }

        Write-CommandResult -Result ([pscustomobject]@{
            Status = 'PASS'
            Command = 'verify'
            Version = $source.Parsed.Version
            Source = $source.Path
            Changelog = $changelogPath
            Projects = $projects
            PublishedAssemblies = $assemblies
            Tag = $tagResult
            CleanWorkingTreeChecked = [bool]$RequireClean
        })
    }
}
