<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>StudyReportEvaluator.App.Tests</AssemblyName>
    <RootNamespace>StudyReportEvaluator.App.Tests</RootNamespace>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StudyReportEvaluator.Core\StudyReportEvaluator.Core.csproj" />
    <ProjectReference Include="..\..\src\StudyReportEvaluator.App\StudyReportEvaluator.App.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Avalonia.Headless.XUnit" />
  </ItemGroup>
</Project>
